import 'package:flutter/foundation.dart';

/// Represents a single location point.
@immutable
class LocationPoint {
  /// Internal database ID.
  final int? id;
  
  /// Unique identifier for this point.
  final String uuid;
  
  /// Latitude in degrees.
  final double latitude;
  
  /// Longitude in degrees.
  final double longitude;
  
  /// Estimated accuracy in meters.
  final double accuracy;
  
  /// Altitude in meters.
  final double? altitude;
  
  /// Altitude accuracy in meters.
  final double? altitudeAccuracy;
  
  /// Speed in meters/second.
  final double? speed;
  
  /// Speed accuracy in meters/second.
  final double? speedAccuracy;
  
  /// Heading in degrees.
  final double? heading;
  
  /// Heading accuracy in degrees.
  final double? headingAccuracy;
  
  /// Timestamp of the location fix (UTC).
  final DateTime timestamp;
  
  /// Provider that generated the fix (e.g., 'fused', 'gps', 'network').
  final String? provider;
  
  /// Whether this location was generated by a mock provider.
  final bool isMock;
  
  /// Battery level (0.0 to 100.0) at the time of the fix.
  final double? batteryLevel;
  
  /// Whether the device was charging at the time of the fix.
  final bool? isCharging;
  
  /// Detected activity (still, walking, running, cycling, vehicle, unknown).
  final String? activity;
  
  /// Tracking mode used to capture this point.
  final String? mode;
  
  /// Session ID this point belongs to.
  final String? sessionId;
  
  /// Shift ID this point belongs to.
  final String? shiftId;
  
  /// User ID this point belongs to.
  final String? userId;
  
  /// Tag for special points (normal, heartbeat, manual, stop, geofence).
  final String tag;
  
  /// Additional extras attached to the point.
  final Map<String, String>? extras;
  
  /// Whether this point has been successfully synced to the backend.
  final bool isSynced;

  /// Creates a new LocationPoint.
  const LocationPoint({
    this.id,
    required this.uuid,
    required this.latitude,
    required this.longitude,
    required this.accuracy,
    this.altitude,
    this.altitudeAccuracy,
    this.speed,
    this.speedAccuracy,
    this.heading,
    this.headingAccuracy,
    required this.timestamp,
    this.provider,
    this.isMock = false,
    this.batteryLevel,
    this.isCharging,
    this.activity,
    this.mode,
    this.sessionId,
    this.shiftId,
    this.userId,
    this.tag = 'normal',
    this.extras,
    this.isSynced = false,
  });

  /// Creates a LocationPoint from a map.
  factory LocationPoint.fromMap(Map<dynamic, dynamic> map) {
    return LocationPoint(
      id: map['id'] as int?,
      uuid: map['uuid'] as String,
      latitude: (map['latitude'] as num).toDouble(),
      longitude: (map['longitude'] as num).toDouble(),
      accuracy: (map['accuracy'] as num).toDouble(),
      altitude: (map['altitude'] as num?)?.toDouble(),
      altitudeAccuracy: (map['altitudeAccuracy'] as num?)?.toDouble(),
      speed: (map['speed'] as num?)?.toDouble(),
      speedAccuracy: (map['speedAccuracy'] as num?)?.toDouble(),
      heading: (map['heading'] as num?)?.toDouble(),
      headingAccuracy: (map['headingAccuracy'] as num?)?.toDouble(),
      timestamp: DateTime.fromMillisecondsSinceEpoch(map['timestamp'] as int, isUtc: true),
      provider: map['provider'] as String?,
      isMock: map['isMock'] as bool? ?? false,
      batteryLevel: (map['batteryLevel'] as num?)?.toDouble(),
      isCharging: map['isCharging'] as bool?,
      activity: map['activity'] as String?,
      mode: map['mode'] as String?,
      sessionId: map['sessionId'] as String?,
      shiftId: map['shiftId'] as String?,
      userId: map['userId'] as String?,
      tag: map['tag'] as String? ?? 'normal',
      extras: (map['extras'] as Map?)?.map((k, v) => MapEntry(k.toString(), v.toString())),
      isSynced: map['isSynced'] as bool? ?? false,
    );
  }

  /// Converts the LocationPoint to a map.
  Map<String, dynamic> toMap() {
    return {
      if (id != null) 'id': id,
      'uuid': uuid,
      'latitude': latitude,
      'longitude': longitude,
      'accuracy': accuracy,
      if (altitude != null) 'altitude': altitude,
      if (altitudeAccuracy != null) 'altitudeAccuracy': altitudeAccuracy,
      if (speed != null) 'speed': speed,
      if (speedAccuracy != null) 'speedAccuracy': speedAccuracy,
      if (heading != null) 'heading': heading,
      if (headingAccuracy != null) 'headingAccuracy': headingAccuracy,
      'timestamp': timestamp.millisecondsSinceEpoch,
      if (provider != null) 'provider': provider,
      'isMock': isMock,
      if (batteryLevel != null) 'batteryLevel': batteryLevel,
      if (isCharging != null) 'isCharging': isCharging,
      if (activity != null) 'activity': activity,
      if (mode != null) 'mode': mode,
      if (sessionId != null) 'sessionId': sessionId,
      if (shiftId != null) 'shiftId': shiftId,
      if (userId != null) 'userId': userId,
      'tag': tag,
      if (extras != null) 'extras': extras,
      'isSynced': isSynced,
    };
  }

  /// Creates a copy of this LocationPoint with the given fields replaced.
  LocationPoint copyWith({
    int? id,
    String? uuid,
    double? latitude,
    double? longitude,
    double? accuracy,
    double? altitude,
    double? altitudeAccuracy,
    double? speed,
    double? speedAccuracy,
    double? heading,
    double? headingAccuracy,
    DateTime? timestamp,
    String? provider,
    bool? isMock,
    double? batteryLevel,
    bool? isCharging,
    String? activity,
    String? mode,
    String? sessionId,
    String? shiftId,
    String? userId,
    String? tag,
    Map<String, String>? extras,
    bool? isSynced,
  }) {
    return LocationPoint(
      id: id ?? this.id,
      uuid: uuid ?? this.uuid,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      accuracy: accuracy ?? this.accuracy,
      altitude: altitude ?? this.altitude,
      altitudeAccuracy: altitudeAccuracy ?? this.altitudeAccuracy,
      speed: speed ?? this.speed,
      speedAccuracy: speedAccuracy ?? this.speedAccuracy,
      heading: heading ?? this.heading,
      headingAccuracy: headingAccuracy ?? this.headingAccuracy,
      timestamp: timestamp ?? this.timestamp,
      provider: provider ?? this.provider,
      isMock: isMock ?? this.isMock,
      batteryLevel: batteryLevel ?? this.batteryLevel,
      isCharging: isCharging ?? this.isCharging,
      activity: activity ?? this.activity,
      mode: mode ?? this.mode,
      sessionId: sessionId ?? this.sessionId,
      shiftId: shiftId ?? this.shiftId,
      userId: userId ?? this.userId,
      tag: tag ?? this.tag,
      extras: extras ?? this.extras,
      isSynced: isSynced ?? this.isSynced,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocationPoint && runtimeType == other.runtimeType && uuid == other.uuid;

  @override
  int get hashCode => uuid.hashCode;

  @override
  String toString() {
    return 'LocationPoint(uuid: $uuid, lat: $latitude, lng: $longitude, acc: $accuracy, ts: $timestamp)';
  }
}
