import 'package:flutter/foundation.dart';
import 'tracking_mode.dart';
import 'battery_policy.dart';
import 'schedule.dart';
import 'geofence.dart';

/// Primary configuration for a tracking session.
@immutable
class TrackingConfig {
  /// The chosen tracking mode.
  final TrackingMode mode;

  /// Desired accuracy for location fixes.
  final LocationAccuracy accuracy;

  /// Base interval for updates (continuous / periodic / hybrid).
  final int? intervalSeconds;

  /// Fastest acceptable interval (continuous).
  final int? fastestIntervalSeconds;

  /// Distance threshold in meters (distanceFilter / hybrid).
  final int? minDistanceMeters;

  /// If the user is stationary, record a point every N minutes (distanceFilter).
  final int? heartbeatMinutes;

  /// Time to wait for a fix before giving up (periodic).
  final int? fixTimeoutSeconds;

  /// Scheduled windows for tracking.
  final List<TrackingWindow>? schedule;

  /// Geofences to trigger detailed tracking.
  final List<Geofence>? geofences;

  /// Trigger condition for geofences ('inside' or 'outside').
  final String? trackWhen;

  /// Condition for hybrid mode ('either' or 'both' distance and time).
  final String? hybridPolicy;

  /// Minimum acceptable accuracy (fixes worse than this are discarded).
  final int minAccuracyMeters;

  /// Maximum age of a valid fix in seconds (discards old cached locations).
  final int maxLocationAgeSeconds;

  /// Discard locations generated by mock location apps.
  final bool discardMockLocations;

  /// Defines tracking behavior on low/critical battery.
  final BatteryPolicy batteryPolicy;

  /// Whether to detect stationary periods to save power and storage.
  final bool detectStops;

  /// Radius to consider as "stopped" when [detectStops] is true.
  final int stopRadiusMeters;

  /// Duration to stay within [stopRadiusMeters] before recording a stop.
  final int stopMinDurationSeconds;

  /// Custom metadata to attach to every captured point in this session.
  final Map<String, String>? extras;

  /// User identifier, attached to all points.
  final String? userId;

  /// Session identifier. If null, a UUID is auto-generated by the plugin.
  final String? sessionId;

  /// Shift identifier.
  final String? shiftId;

  /// Duration after which to automatically stop tracking.
  final Duration? stopAfter;

  /// Specific date and time to automatically stop tracking.
  final DateTime? stopAt;

  /// Time in seconds to keep the notification visible after capturing a location.
  final int? notificationTimeout;

  const TrackingConfig({
    required this.mode,
    this.accuracy = LocationAccuracy.balanced,
    this.intervalSeconds,
    this.fastestIntervalSeconds,
    this.minDistanceMeters,
    this.heartbeatMinutes,
    this.fixTimeoutSeconds,
    this.schedule,
    this.geofences,
    this.trackWhen,
    this.hybridPolicy,
    this.minAccuracyMeters = 100,
    this.maxLocationAgeSeconds = 60,
    this.discardMockLocations = true,
    this.batteryPolicy = const BatteryPolicy(),
    this.detectStops = false,
    this.stopRadiusMeters = 50,
    this.stopMinDurationSeconds = 180,
    this.extras,
    this.userId,
    this.sessionId,
    this.shiftId,
    this.stopAfter,
    this.stopAt,
    this.notificationTimeout,
  });

  factory TrackingConfig.fromMap(Map<dynamic, dynamic> map) {
    return TrackingConfig(
      mode: TrackingMode.values.firstWhere(
        (e) => e.name == map['mode'],
        orElse: () => TrackingMode.continuous,
      ),
      accuracy: LocationAccuracy.values.firstWhere(
        (e) => e.name == map['accuracy'],
        orElse: () => LocationAccuracy.balanced,
      ),
      intervalSeconds: map['intervalSeconds'] as int?,
      fastestIntervalSeconds: map['fastestIntervalSeconds'] as int?,
      minDistanceMeters: map['minDistanceMeters'] as int?,
      heartbeatMinutes: map['heartbeatMinutes'] as int?,
      fixTimeoutSeconds: map['fixTimeoutSeconds'] as int?,
      schedule: (map['schedule'] as List?)
          ?.map((e) => TrackingWindow.fromMap(e as Map))
          .toList(),
      geofences: (map['geofences'] as List?)
          ?.map((e) => Geofence.fromMap(e as Map))
          .toList(),
      trackWhen: map['trackWhen'] as String?,
      hybridPolicy: map['hybridPolicy'] as String?,
      minAccuracyMeters: map['minAccuracyMeters'] as int? ?? 100,
      maxLocationAgeSeconds: map['maxLocationAgeSeconds'] as int? ?? 60,
      discardMockLocations: map['discardMockLocations'] as bool? ?? true,
      batteryPolicy: map['batteryPolicy'] != null
          ? BatteryPolicy.fromMap(map['batteryPolicy'] as Map)
          : const BatteryPolicy(),
      detectStops: map['detectStops'] as bool? ?? false,
      stopRadiusMeters: map['stopRadiusMeters'] as int? ?? 50,
      stopMinDurationSeconds: map['stopMinDurationSeconds'] as int? ?? 180,
      extras: (map['extras'] as Map?)?.map((k, v) => MapEntry(k.toString(), v.toString())),
      userId: map['userId'] as String?,
      sessionId: map['sessionId'] as String?,
      shiftId: map['shiftId'] as String?,
      stopAfter: map['stopAfterMs'] != null 
          ? Duration(milliseconds: map['stopAfterMs'] as int) 
          : null,
      stopAt: map['stopAt'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['stopAt'] as int, isUtc: true)
          : null,
      notificationTimeout: (map['notificationTimeout'] as int?) != null 
          ? ((map['notificationTimeout'] as int) < 5 ? 5 : map['notificationTimeout'] as int)
          : 5,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'mode': mode.name,
      'accuracy': accuracy.name,
      if (intervalSeconds != null) 'intervalSeconds': intervalSeconds,
      if (fastestIntervalSeconds != null) 'fastestIntervalSeconds': fastestIntervalSeconds,
      if (minDistanceMeters != null) 'minDistanceMeters': minDistanceMeters,
      if (heartbeatMinutes != null) 'heartbeatMinutes': heartbeatMinutes,
      if (fixTimeoutSeconds != null) 'fixTimeoutSeconds': fixTimeoutSeconds,
      if (schedule != null) 'schedule': schedule!.map((e) => e.toMap()).toList(),
      if (geofences != null) 'geofences': geofences!.map((e) => e.toMap()).toList(),
      if (trackWhen != null) 'trackWhen': trackWhen,
      if (hybridPolicy != null) 'hybridPolicy': hybridPolicy,
      'minAccuracyMeters': minAccuracyMeters,
      'maxLocationAgeSeconds': maxLocationAgeSeconds,
      'discardMockLocations': discardMockLocations,
      'batteryPolicy': batteryPolicy.toMap(),
      'detectStops': detectStops,
      'stopRadiusMeters': stopRadiusMeters,
      'stopMinDurationSeconds': stopMinDurationSeconds,
      if (extras != null) 'extras': extras,
      if (userId != null) 'userId': userId,
      if (sessionId != null) 'sessionId': sessionId,
      if (shiftId != null) 'shiftId': shiftId,
      if (stopAfter != null) 'stopAfterMs': stopAfter!.inMilliseconds,
      if (stopAt != null) 'stopAt': stopAt!.millisecondsSinceEpoch,
      if (notificationTimeout != null) 'notificationTimeout': notificationTimeout,
    };
  }

  TrackingConfig copyWith({
    TrackingMode? mode,
    LocationAccuracy? accuracy,
    int? intervalSeconds,
    int? fastestIntervalSeconds,
    int? minDistanceMeters,
    int? heartbeatMinutes,
    int? fixTimeoutSeconds,
    List<TrackingWindow>? schedule,
    List<Geofence>? geofences,
    String? trackWhen,
    String? hybridPolicy,
    int? minAccuracyMeters,
    int? maxLocationAgeSeconds,
    bool? discardMockLocations,
    BatteryPolicy? batteryPolicy,
    bool? detectStops,
    int? stopRadiusMeters,
    int? stopMinDurationSeconds,
    Map<String, String>? extras,
    String? userId,
    String? sessionId,
    String? shiftId,
    Duration? stopAfter,
    DateTime? stopAt,
    int? notificationTimeout,
  }) {
    return TrackingConfig(
      mode: mode ?? this.mode,
      accuracy: accuracy ?? this.accuracy,
      intervalSeconds: intervalSeconds ?? this.intervalSeconds,
      fastestIntervalSeconds: fastestIntervalSeconds ?? this.fastestIntervalSeconds,
      minDistanceMeters: minDistanceMeters ?? this.minDistanceMeters,
      heartbeatMinutes: heartbeatMinutes ?? this.heartbeatMinutes,
      fixTimeoutSeconds: fixTimeoutSeconds ?? this.fixTimeoutSeconds,
      schedule: schedule ?? this.schedule,
      geofences: geofences ?? this.geofences,
      trackWhen: trackWhen ?? this.trackWhen,
      hybridPolicy: hybridPolicy ?? this.hybridPolicy,
      minAccuracyMeters: minAccuracyMeters ?? this.minAccuracyMeters,
      maxLocationAgeSeconds: maxLocationAgeSeconds ?? this.maxLocationAgeSeconds,
      discardMockLocations: discardMockLocations ?? this.discardMockLocations,
      batteryPolicy: batteryPolicy ?? this.batteryPolicy,
      detectStops: detectStops ?? this.detectStops,
      stopRadiusMeters: stopRadiusMeters ?? this.stopRadiusMeters,
      stopMinDurationSeconds: stopMinDurationSeconds ?? this.stopMinDurationSeconds,
      extras: extras ?? this.extras,
      userId: userId ?? this.userId,
      sessionId: sessionId ?? this.sessionId,
      shiftId: shiftId ?? this.shiftId,
      stopAfter: stopAfter ?? this.stopAfter,
      stopAt: stopAt ?? this.stopAt,
      notificationTimeout: notificationTimeout ?? this.notificationTimeout,
    );
  }
}
